---
- name: Install and configure ClickHouse
  hosts: clickhouse
  become: true
  tags: clickhouse
  vars_files:
    - group_vars/clickhouse/vars.yml
  roles:
    - role: clickhouse
  tasks:
    - name: Create database logs
      ansible.builtin.command: clickhouse-client -q "CREATE DATABASE IF NOT EXISTS logs"
      register: create_db
      changed_when: create_db.rc == 0
      failed_when: false

- name: Install and configure Vector
  hosts: vector
  become: true
  tags: vector
  vars_files:
    - group_vars/vector/vars.yml
  roles:
    - role: vector

- name: Install and configure LightHouse
  hosts: lighthouse
  become: true
  tags: lighthouse
  vars_files:
    - group_vars/lighthouse/vars.yml
  roles:
    - role: lighthouse