---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 213.165.209.175
vector:
  hosts:
    vector-01:
      ansible_host: 178.154.193.138
lighthouse:
  hosts:
    lighthouse-01:
          ansible_host: 217.28.224.83
